project:
  type: book
  output-dir: _report
  
# quarto publish netlify --no-render --no-browser --no-prompt  

book:
  title: "Spending on Homelessness by the City-County of San Francisco"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - sanfranservices.qmd
    - studies.qmd
    - references.qmd
    - appendix.qmd

bibliography: _bibliography.bib
nocite: |
  @*

execute: 
  cache: true
  echo: false
  warning: false
  include: false

format:
  html:
    css: style.css  # for div datatables wrapper
    theme: cosmo
    self-contained: false
  # pdf:
  #   documentclass: scrreprt





