project:
  type: book
  output-dir: _report
  
# quarto publish netlify --no-render --no-browser --no-prompt  

book:
  title: "Spending on Homelessness by the City-County of San Francisco"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - sanfranservices.qmd
    - spending.qmd
    - studies.qmd
    - references.qmd
    - appendix.qmd

bibliography: _bibliography.bib
nocite: |
  @*

execute:
  eval: true
  include: false  
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: auto  # during global project renders, re-render only when source changes

format:
  html:
    css: style.css  # for div datatables wrapper
    theme: cosmo
    self-contained: false
  # pdf:
  #   documentclass: scrreprt





