# Conclusions

San Francisco's four major agencies involved in homelessness-related programs are spending, in aggregate, an average of \$1.5 billion annually on homelessness-related services. Approximately \$1.1 billion of this spending is from sources supported directly by local taxpayers, with the remainder paid by the state or federal government, some of which is paid indirectly by San Francisco taxpayers.

In addition, at least a dozen other agencies are involved in services related to homelessness. There are no comprehensive data on the spending of these other agencies, but the amounts devoted to homelessness services are likely to be far smaller than the spending by the four major agencies.

Homelesssness-related funding has risen dramatically in recent years, and increased 166 percent between 2019-20 and 2020-21. In an effort to put housing and programs in place quickly, under legislation adopted by the board of supervisors, city agencies have engaged in extensive no-bid contracting. This creates risks of inappropriate contracting.

The city's dramatic spending increases and the increases in housing they have supported appear to finally be changing the trends in homelessness. The number of unsheltered homeless people fell by 15 percent between a count taken in 2019 and the latest count, taken in 2022. We see a glimmer of good news also in exits from homelessness, which rose sharply in 2022.

The city faces at least four major challenges in its budgeting for homelessness.

First, a large share of current funding for homelessness is related to one-time or temporary resources from the state and federal governments, particularly in response to COVID-19. Several of these funding sources are winding down. The city will have to manage and alter its programs in response to changes in the level of state and federal funding.

Second, locally supported revenue is likely to be strained, also. Economic weakness in the post-COVID period, including office vacancies and declines in property values are likely to depress city general fund revenue and also Proposition C revenue devoted to Our City, Our Homes spending.

Third, much of the funding in recent years has been for acquisition of housing, particularly permanent supportive housing. It will need to focus increasingly on managing and operating this housing portfolio.

Finally, in an effort to put housing and programs in place quickly, under legislation adopted by the board of supervisors, city agencies have engaged in extensive no-bid contracting. This creates risks of inappropriate contracting. The city will have to beef up its ability to oversee and manage these contracts.
